### ISSUE TITLE
Roadmap for 3.x

### ISSUE THREAD

**Issue by leftstick** [leftstick/express-api-bootstrap#2]
3.x
=============

Following are plans will be finished in the future.

* [ ] Whole architecture re-design with spring-boot like flavor(zore config with default preset; convention over configuration; cli; )
* [ ] Whole framework re-implement in Typescript for more solid structure
* [ ] Plugin system should be provided
* [ ] Typescript will be enforced as develop language for users
* [ ] DI powered by [typedi](https://github.com/typestack/typedi)
* [ ] API with better annotation experiences
